version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=lucas
      - DB_PASSWORD=1234
      - DB=ng_cash
      - SECRET_KEY=ng_cash
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ng_cash
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lucas -d ng_cash"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ng_cash:/var/lib/postgresql/data

volumes:
  ng_cash:
    driver: local
